# Source: lighthouse/templates/oauthsecret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: unspecified-complex-type
  labels:
    app: external-dns
    chart: "external-dns-0.5.3"
    release: "external-dns"
    heritage: "Helm"
spec:
  backendType: azureKeyVault
  keyVaultName: twilightSparkle
  data:
    - name: hmac
      key: unspecified-complex-type
      property: hmac
    - name: git_token
      key: unspecified-complex-type
      property: git_token
  template:
    metadata:
      labels:
        app: external-dns
        chart: "external-dns-0.5.3"
        release: "external-dns"
        heritage: "Helm"
    type: Opaque
