apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gpg
  namespace: jx
spec:
  backendType: local
  data:
  - name: passphrase
    key: gpg
    property: passphrase
  template:
    type: Opaque
