# Source: jxboot-helmfile-resources/templates/maven-settings-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: environment
spec:
  data:
  - secretKey: settings.xml
    remoteRef:
      key: jx/mavenSettings
      property: settingsXml
  - secretKey: settings-security.xml
    remoteRef:
      key: jx/mavenSettings
      property: securityXml
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
