# Source: tekton/templates/250-git-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: knative-git-user-pass
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"knative-git-user-pass","properties":[{"name":"username","question":"the
      pipeline username","help":"the user name used by pipelines running in Jenkins
      X","generator":"gitOperator.username"},{"name":"token","question":"the pipeline
      token or password","help":"the token or password used by pipelines running in
      Jenkins X","generator":"gitOperator.password"}],"mandatory":true}'
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: vault-infra
  data:
  - name: password
    key: secret/data/jx/pipelineUser
    property: token
  - name: username
    key: secret/data/jx/pipelineUser
    property: username
  template:
    metadata:
      annotations:
        tekton.dev/git-0: "https://github.com"
    type: kubernetes.io/basic-auth