# Source: tekton/templates/250-docker-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: knative-docker-user-pass
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"knative-docker-user-pass","properties":[{"name":"username","question":"Docker
      Registry username","help":"The username used to access the external docker registry","defaultValue":"admin"},{"name":"password","question":"Docker
      Registry password","help":"The password used to access the external docker registry","generator":"password"}],"mandatory":true}'
  labels:
    gitops.jenkins-x.io/pipeline: environment
spec:
  data:
  - secretKey: password
    remoteRef:
      key: jx/docker
      property: password
  - secretKey: username
    remoteRef:
      key: jx/docker
      property: username
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        annotations:
          tekton.dev/docker-0: ''
      type: kubernetes.io/basic-auth
