# Source: tekton/templates/250-docker-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: knative-docker-user-pass
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"knative-docker-user-pass","properties":[{"name":"username","question":"Docker
      Registry username","help":"The username used to access the external docker registry","defaultValue":"admin"},{"name":"password","question":"Docker
      Registry password","help":"The password used to access the external docker registry","generator":"password"}],"mandatory":true}'
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: vault-infra
  data:
  - name: password
    key: secret/data/jx/docker
    property: password
  - name: username
    key: secret/data/jx/docker
    property: username
  template:
    metadata:
      annotations:
        tekton.dev/docker-0: ""
    type: kubernetes.io/basic-auth