apiVersion: secret.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: jenkins-maven-settings
    properties:
    - name: settingsXml
      question: Maven settings XML contents
      help: This is the maven settings XML which is mounted for Java builds
      template: |-
        <settings>
            <localRepository>/home/jenkins/.mvnrepository</localRepository>
            <!--This sends everything else to /public -->
        {{- if and (hasKey .Requirements "repository") (eq .Requirements.repository "bucketrepo") }}
              <mirrors>
                  <mirror>
                      <id>bucketrepo</id>
                      <name>bucketrepo mirror</name>
                      <mirrorOf>*</mirrorOf>
                      <url>http://bucketrepo/bucketrepo/</url>
                  </mirror>
                </mirrors>
        {{- else if and (hasKey .Requirements "repository") (eq .Requirements.repository "none") }}
              <mirrors>
                <mirror>
                  <id>central</id>
                  <name>US Central</name>
                  <url>https://repo.maven.apache.org/maven2</url>
                  <mirrorOf>central</mirrorOf>
                </mirror>
                <mirror>
                  <id>UK</id>
                  <name>UK Central</name>
                  <url>https://uk.maven.org/maven2</url>
                  <mirrorOf>central</mirrorOf>
                </mirror>
              </mirrors>
        {{- else }}
              <mirrors>
                <mirror>
                    <id>nexus</id>
                    <name>nexus mirror</name>
                    <mirrorOf>external:*</mirrorOf>
                    <url>http://nexus/repository/maven-group/</url>
                </mirror>
              </mirrors>
        {{- end }}

            <!-- lets disable the download progress indicator that fills up logs -->
            <interactiveMode>false</interactiveMode>

            <servers>
                <server>
                    <id>local-nexus</id>
                    <username>{{ secret "nexus" "username" | default "admin"}}</username>
                    <password>{{ secret "nexus" "password" }}</password>
                </server>
                <server>
                    <id>nexus</id>
                    <username>{{ secret "nexus" "username" | default "admin"}}</username>
                    <password>{{ secret "nexus" "password" }}</password>
                </server>
                <server>
                    <id>chartmuseum</id>
                    <username>{{ secret "jenkins-x-chartmuseum" "username" }}</username>
                    <password>{{ secret "jenkins-x-chartmuseum" "password" }}</password>
                </server>
                <server>
                    <id>bucketrepo</id>
                    <username>{{ secret "jenkins-x-bucketrepo" "username" }}</username>
                    <password>{{ secret "jenkins-x-bucketrepo" "password" }}</password>
                </server>
                <server>
                    <id>oss-sonatype-staging</id>
                    <username>{{ secret "sonatype" "username" }}</username>
                    <password>{{ secret "sonatype" "password" }}</password>
                </server>
                <server>
                    <id>docker.io</id>
                    <username>{{ secret "docker-hub" "username" }}</username>
                    <password>{{ secret "docker-hub" "password" }}</password>
                </server>
            </servers>

            <profiles>
                <profile>
                    <id>nexus</id>
                    <properties>
        {{- if and (hasKey .Requirements "repository") (eq .Requirements.repository "bucketrepo") }}
                      <altDeploymentRepository>local-nexus::default::http://bucketrepo/bucketrepo/deploy/maven-snapshots/</altDeploymentRepository>
                      <altReleaseDeploymentRepository>local-nexus::default::http://bucketrepo/bucketrepo/deploy/maven-releases/</altReleaseDeploymentRepository>
                      <altSnapshotDeploymentRepository>local-nexus::default::http://bucketrepo/bucketrepo/deploy/maven-snapshots/</altSnapshotDeploymentRepository>
        {{- else if and (hasKey .Requirements "repository") (eq .Requirements.repository "none") }}
        {{- else }}
                      <altDeploymentRepository>local-nexus::default::http://nexus/repository/maven-snapshots/</altDeploymentRepository>
                      <altReleaseDeploymentRepository>local-nexus::default::http://nexus/repository/maven-releases/</altReleaseDeploymentRepository>
                      <altSnapshotDeploymentRepository>local-nexus::default::http://nexus/repository/maven-snapshots/</altSnapshotDeploymentRepository>
        {{- end }}
                    </properties>

                    <repositories>
                        <repository>
                            <id>central</id>
                            <url>http://central</url>
                            <releases><enabled>true</enabled></releases>
                            <snapshots><enabled>true</enabled></snapshots>
                        </repository>
                    </repositories>
                    <pluginRepositories>
                        <pluginRepository>
                            <id>central</id>
                            <url>http://central</url>
                            <releases><enabled>true</enabled></releases>
                            <snapshots><enabled>true</enabled></snapshots>
                        </pluginRepository>
                    </pluginRepositories>
                </profile>
                <profile>
                    <id>repo.jenkins-ci.org</id>
                    <properties>
                        <altDeploymentRepository>repo.jenkins-ci.org::default::https://repo.jenkins-ci.org/releases/</altDeploymentRepository>
                        <altReleaseDeploymentRepository>repo.jenkins-ci.org::default::https://repo.jenkins-ci.org/releases/</altReleaseDeploymentRepository>
                        <altSnapshotDeploymentRepository>repo.jenkins-ci.org::default::https://repo.jenkins-ci.org/snapshots/</altSnapshotDeploymentRepository>
                    </properties>

                </profile>
                <profile>
                    <id>maven.jenkins-ci.org</id>
                    <properties>
                        <altDeploymentRepository>maven.jenkins-ci.org::default::https://maven.jenkins-ci.org/releases/</altDeploymentRepository>
                        <altReleaseDeploymentRepository>maven.jenkins-ci.org::default::https://maven.jenkins-ci.org/releases/</altReleaseDeploymentRepository>
                        <altSnapshotDeploymentRepository>maven.jenkins-ci.org::default::https://maven.jenkins-ci.org/snapshots/</altSnapshotDeploymentRepository>
                    </properties>

                </profile>
                <profile>
                    <id>release</id>
                    <properties>
                        <gpg.executable>gpg</gpg.executable>
                        <!-- TODO use: .Parameters.gpg.passphrase when it is always populated -->
                        <gpg.passphrase>{{ secret "gpg" "passphrase" }}</gpg.passphrase>
                    </properties>
                </profile>
            </profiles>

            <activeProfiles>
                <activeProfile>nexus</activeProfile>
            </activeProfiles>
        </settings>
    - name: securityXml
      question: Maven security XML contents
      help: This is the maven security XML which is mounted for Java builds
      defaultValue: |-
        <settingsSecurity/>
  - name: jenkins-docker-cfg
    properties:
    - name: config.json
      question: Docker JSON Configuration
      help: This is the docker JSON configuration for authenticating with container registries
      template: |-
        {
          # plugin custom container registries here
          "auths":{
            "{{ .Parameters.docker.url  }}": {
                "auth": {{ printf "%s:%s" .Parameters.docker.username .Parameters.docker.password | b64enc | quote}},
                "email": {{ .Parameters.docker.email | quote}}
            }
          },

        {{- if eq .Requirements.cluster.provider "gke" }}

          # lets enable GCR container builds
          "credHelpers": {
              "gcr.io": "gcr",
              "us.gcr.io": "gcr",
              "eu.gcr.io": "gcr",
              "asia.gcr.io": "gcr",
              "staging-k8s.gcr.io": "gcr"
          }

        {{- else if eq .Requirements.cluster.provider "eks" }}

          # lets enable ECR container builds
          "credHelpers": {
            "{{ .Requirements.cluster.registry }}": "ecr-login"
          }

        {{- else if eq .Requirements.cluster.provider "aws" }}

          # lets enable ECR container builds
          "credsStore": "ecr-login"

        {{- else if eq .Requirements.cluster.provider "aws" }}

          # lets enable ACR container builds
          "credsStore": "acr"

        {{- end }}
        }


