apiVersion: secret.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: knative-git-user-pass
    properties:
    - name: username
      key: secret/data/jx/pipelineUser
      question: the pipeline username
      help: the user name used by pipelines running in Jenkins X
      generator: gitOperator.username
    - name: token
      key: secret/data/jx/pipelineUser
      question: the pipeline token or password
      help: the token or password used by pipelines running in Jenkins X
      generator: gitOperator.password
  - name: knative-docker-user-pass
    properties:
    - name: username
      question: Docker Registry username
      help: The username used to access the external docker registry
      defaultValue: admin
    - name: password
      question: Docker Registry password
      help: The password used to access the external docker registry
      generator: password

