# Source: lighthouse/templates/oauthsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unspecified-complex-type
  labels:
    app: external-dns
    chart: "external-dns-0.5.3"
    release: "external-dns"
    heritage: "Helm"
spec:
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  data:
  - secretKey: hmac
    remoteRef:
      key: unspecified-complex-type
      property: hmac
      version: AWSPREVIOUS
  - secretKey: git_token
    remoteRef:
      key: unspecified-complex-type
      property: git_token
      version: AWSPREVIOUS
  target:
    template:
      metadata:
        labels:
          app: external-dns
          chart: "external-dns-0.5.3"
          release: "external-dns"
          heritage: "Helm"
      type: Opaque
