apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lighthouse-oauth-token
  namespace: jx
spec:
  data:
  - secretKey: oauth
    remoteRef:
      key: lighthouse-oauth-token
      property: token
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          app: lighthouse-lighthouse
          chart: lighthouse-0.0.633
          heritage: Helm
          release: lighthouse
      type: Opaque
