apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-with-stringdata
  namespace: jx
spec:
  data:
  - secretKey: token
    remoteRef:
      key: secret-with-stringdata
      property: token
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          app: some-app
      type: Opaque
