apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-with-stringdata
  namespace: jx
spec:
  backendType: azureKeyVault
  keyVaultName: azureSuperSecretVault
  data:
  - key: secret-with-stringdata
    name: token
    property: token
  template:
    metadata:
      labels:
        app: some-app
    type: Opaque
