# Source: lighthouse/templates/oauthsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: simple-secret-property
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-0.0.633"
    release: "lighthouse"
    heritage: "Helm"
spec:
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  data:
  - secretKey: azure.json
    remoteRef:
      key: azure-secret-name
      property: customProperty
      version: AWSPREVIOUS
  target:
    template:
      metadata:
        labels:
          app: lighthouse-lighthouse
          chart: "lighthouse-0.0.633"
          release: "lighthouse"
          heritage: "Helm"
      type: Opaque
