# Source: bucketrepo/templates/config-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bucketrepo-config
  namespace: jx
spec:
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  data:
  - secretKey: config.yaml
    remoteRef:
      key: bucketrepo/config
      property: config.yaml
  target:
    template:
      metadata:
        annotations:
          config/checksum: c41b5c22daadb25e478a6d0f1ccf4d8fd388a3851bc559a9adf789d902fe80b0
      type: Opaque
