apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gpg
  namespace: jx
spec:
  data:
  - secretKey: passphrase
    remoteRef:
      key: gpg
      property: passphrase
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  target:
    template:
      type: Opaque
