apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus
  labels:
    app: nexus-nexus
    chart: "nexus-0.1.37"
    release: "nexus"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"nexus","properties":[{"name":"username","question":"nexus user name","help":"The username used to authenticate with nexus","defaultValue":"admin"},{"name":"password","question":"nexus password","help":"The password to authenticate with nexus","defaultValue":"admin123","minLength":5,"maxLength":41}],"mandatory":true}'
spec:
  backendType: azureKeyVault
  keyVaultName: azureSuperSecretVault
  data:
  - name: password
    key: nexus
    property: password
  template:
    metadata:
      labels:
        app: nexus-nexus
        chart: "nexus-0.1.37"
        release: "nexus"
        heritage: "Helm"
      annotations:
        secret.jenkins-x.io/schema-object: '{"name":"nexus","properties":[{"name":"username","question":"nexus user name","help":"The username used to authenticate with nexus","defaultValue":"admin"},{"name":"password","question":"nexus password","help":"The password to authenticate with nexus","defaultValue":"admin123","minLength":5,"maxLength":41}],"mandatory":true}'
    type: Opaque
