# Source: jxboot-helmfile-resources/templates/maven-settings-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: "123456"
  data:
  - name: settings.xml
    key: jx-maven-settings
    property: settingsXml
  - name: settings-security.xml
    key: jx-maven-settings
    property: securityXml
  template:
    type: Opaque
