apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonatype
  namespace: jx
spec:
  backendType: gcpSecretsManager
  projectId: "123456"
  data:
  - name: password
    key: sonatype
    property: password
  - name: username
    key: sonatype
    property: username
  template:
    type: Opaque
