# Source: lighthouse/templates/oauthsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: a-dns-type-secret
  labels:
    app: external-dns
    chart: "external-dns-0.5.3"
    release: "external-dns"
    heritage: "Helm"
spec:
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  data:
  - secretKey: azure.json
    remoteRef:
      key: azure-secret-name
      property: azure.json
  target:
    template:
      metadata:
        labels:
          app: external-dns
          chart: "external-dns-0.5.3"
          release: "external-dns"
          heritage: "Helm"
      type: Opaque
