apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonatype
  namespace: jx
spec:
  backendType: vault
  data:
  - name: password
    key: secret/data/sonatype
    property: password
  - name: username
    key: secret/data/sonatype
    property: username
  template:
    type: Opaque
