# Source: lighthouse/templates/oauthsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lighthouse-oauth-token
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-0.0.633"
    release: "lighthouse"
    heritage: "Helm"
spec:
  secretStoreRef:
    name: jx-secret-store
    kind: ClusterSecretStore
  target:
    template:
      data:
        oauth: pinkiepie
      metadata:
        labels:
          app: lighthouse-lighthouse
          chart: "lighthouse-0.0.633"
          release: "lighthouse"
          heritage: "Helm"
      type: Opaque
  data:
  - secretKey: anotherkey
    remoteRef:
      key: lighthouse/oauth/token
      property: anotherkey
