apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: lint
spec:
  pipelineSpec:
    tasks:
    - name: jx-secret-lint
      resources: {}
      timeout: 1h30m0s
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - image: golangci/golangci-lint:v1.50.1-alpine@sha256:a392d4e44049a444a927878792dae9534075ec57880e0657647ce818bd8278c2
          name: make-lint
          resources: {}
          script: |
            #!/bin/sh
            golangci-lint run --deadline 60m0s
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h30m0s
status: {}
